name: Build Docs

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: >
            docs-build
            ${{ runner.os }}
            ${{ env.pythonLocation }}
            ${{ hashFiles('pyproject.toml') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -e .[doc]

      - name: Build docs site
        run: mkdocs build

      - name: Store docs site
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: site
