name: CI

on:
  push:
    branches:
      - main
    tags:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Docker build and push
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: guigze
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Start build docker image
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: >
            guigze/botwit:latest,
            guigze/botwit:${{ env.RELEASE_VERSION }},
            guigze/botwit:${{ github.sha }}
